version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noto-backend-prod
    ports:
      - "127.0.0.1:8080:8080" # Mais seguro em produção
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/noto-db}
      - PORT=8080
      - ADDRESS=http://localhost
      - JWT_SECRET=${JWT_SECRET:-segredo-jwt-producao}
      - EXPIRE_TIME=3600
      - API_KEY=${API_KEY:-chave-api-producao}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD:-senha-padrao-producao}
      - NODE_ENV=production
    restart: always
    networks:
      - noto-network-prod

networks:
  noto-network-prod:
    name: noto-network-prod
    external: true
